# apiVersion: v1
# kind: Config
# clusters:
# - cluster:
#     certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJMU1EZ3hNREEyTXpJMU1sb1hEVE0xTURnd09UQTJNekkxTWxvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3VSCi9wZStXeGJDeVhGcDlNOVNPYm9KRDcwWERIWFprL2E0YzlUYk53KzNnMGYvWmQyYWJTOEFQVXJSZFpKdzN6ZjYKb2dIWUFrY3p5Wi8wS0xkUzVmSFYzWUJhRDZyNU5kU2J5ZHhaU2lQQ3h2cUI3TkJrTkw0Zmp1c2Ewbmk5c0dMdwpTbVVIZEliK2NEN0VnaDRCUkF1Q1JBbjJWa0dKYmprR1Z5SHNVQkRJZ3dHR0xkME9oc1FFVXN1dTNBYks1akFZCkpEMGpZaXYrVVkxSGNRRmhBbjV0OThXT1IwMldMaytveUJhSkRWNzNEM0NMTndNWlR1VTNiSzV3enVWdmNseWEKVzdmMisybFg5eW5iT3NTMHBJK2VxcXFoZUd4SjIwdUZkblpuQlVvWkVzbzluNFNlYndqOWpENENSVzNlTzlTUwo0RVp1WVBKT3Y3Z2M4S09vWXBNQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJRSWgzeU5kN0hSbktacyt5T28yZVpNU093S0FUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFqUUIrZ1F0RgprUVZZcnhZUFNHWjlmNUc5cHc2YTdKbXBTSkg2RkNZU0R4N1ZqWm9zYXZKSXFRQ0FPSDVmaFBUeUNNYU9QNHAyCllFYXR3Z08xWmJlQ09HRnVYRVFYalVxbDRQaGdPVjlXTjdjdXdXWTEzR2JDYXVUeHlTU2lqRjVqRGd2WlN6NEsKWUhSTmNuYmptR0oyWkM1aUhSZlE1dWVTeDg2R0FkaGFWZkc0ekVtV0dPdjk3bC9sakZ1U2hjdmQvUDU2ZjJPWApIakdTanZQU2JMZzZFcHNHVWlXa2VCT0FFL0xibEVrYUpMeFE5bTR2OHRHRThKQnEvS2l3UkV3RWhIWVpCYkpqCldDRXBYKy9zTmo2NTBHK3hLcStZb3gxbHRmQzBSMnl4SGkyV25TNnVQNEJjc21RaWNpalFneWI1WHpuY0tGNHEKMUU5ak94M0hhQXVuVkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg
#     server: https://192.168.49.2:8443
#   name: minikube
# contexts:
# - context:
#     cluster: minikube
#     namespace: new-travel-api
#     user: jenkins-sa
#   name: jenkins-context
# current-context: jenkins-context
# users:
# - name: jenkins-sa
#   user:
#     token: apiVersion:v1
# kind: Config
# clusters:
# - cluster:
#     certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJ... (long base64)
#     server: https://192.168.49.2:8443
#   name: minikube
# contexts:
# - context:
#     cluster: minikube
#     namespace: new-travel-api
#     user: jenkins-sa
#   name: jenkins-context
# current-context: jenkins-context
# users:
# - name: jenkins-sa
#   user:
#     token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ild3aDFQakVFc0MyMzF4THlUSlhnQTlucHNveENQWHAta2NERXdQWThEMlUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzU2NDQ4NzQyLCJpYXQiOjE3NTY0NDUxNDIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYTZiYWE4MDYtMWM4Yy00MjExLTgxYmQtNDA4MDQzMzRhMzM5Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJuZXctdHJhdmVsLWFwaSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJqZW5raW5zLXNhIiwidWlkIjoiYjc1OWVkOGYtODhmMy00ZjEyLWEzYTUtODU5MTg1OWM5ODM3In19LCJuYmYiOjE3NTY0NDUxNDIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpuZXctdHJhdmVsLWFwaTpqZW5raW5zLXNhIn0.eGgOy2NdT-hrUBTlxAkEX0ILekkdRAk_rHtT6JjJ4SF-pm4DJ1yFkhNEas6DyaIUUiKBd89zFNOwZjadv0GYXIIN-mSLLy_hnq6YKkaofvFmrlK6fk2RlD9D0kijkN_fb7eRW39d-wjDJdGogeFkjhzqHeh4shsStTZ2BSrPolaQ1UxVLm90qQYXzq_r4G9CnkgFFYxWpOJrw1aBdqSGPAlSxNEYUalWwjBiuALyYkuIg8n2gnPI1LAjGR97vX0kUZgInNqVdydGwmvaXGkQv36KLLUE6lmwLss9sxyn4EJXQWEji5H0tf2FuQUlrazrZbJEabEix0eYkNeeSIAjsQ
 

apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJMU1EZ3hNREEyTXpJMU1sb1hEVE0xTURnd09UQTJNekkxTWxvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3VSCi9wZStXeGJDeVhGcDlNOVNPYm9KRDcwWERIWFprL2E0YzlUYk53KzNnMGYvWmQyYWJTOEFQVXJSZFpKdzN6ZjYKb2dIWUFrY3p5Wi8wS0xkUzVmSFYzWUJhRDZyNU5kU2J5ZHhaU2lQQ3h2cUI3TkJrTkw0Zmp1c2Ewbmk5c0dMdwpTbVVIZEliK2NEN0VnaDRCUkF1Q1JBbjJWa0dKYmprR1Z5SHNVQkRJZ3dHR0xkME9oc1FFVXN1dTNBYks1akFZCkpEMGpZaXYrVVkxSGNRRmhBbjV0OThXT1IwMldMaytveUJhSkRWNzNEM0NMTndNWlR1VTNiSzV3enVWdmNseWEKVzdmMisybFg5eW5iT3NTMHBJK2VxcXFoZUd4SjIwdUZkblpuQlVvWkVzbzluNFNlYndqOWpENENSVzNlTzlTUwo0RVp1WVBKT3Y3Z2M4S09vWXBNQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJRSWgzeU5kN0hSbktacyt5T28yZVpNU093S0FUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFqUUIrZ1F0RgprUVZZcnhZUFNHWjlmNUc5cHc2YTdKbXBTSkg2RkNZU0R4N1ZqWm9zYXZKSXFRQ0FPSDVmaFBUeUNNYU9QNHAyCllFYXR3Z08xWmJlQ09HRnVYRVFYalVxbDRQaGdPVjlXTjdjdXdXWTEzR2JDYXVUeHlTU2lqRjVqRGd2WlN6NEsKWUhSTmNuYmptR0oyWkM1aUhSZlE1dWVTeDg2R0FkaGFWZkc0ekVtV0dPdjk3bC9sakZ1U2hjdmQvUDU2ZjJPWApIakdTanZQU2JMZzZFcHNHVWlXa2VCT0FFL0xibEVrYUpMeFE5bTR2OHRHRThKQnEvS2l3UkV3RWhIWVpCYkpqCldDRXBYKy9zTmo2NTBHK3hLcStZb3gxbHRmQzBSMnl4SGkyV25TNnVQNEJjc21RaWNpalFneWI1WHpuY0tGNHEKMUU5ak94M0hhQXVuVkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg
    server: http://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: new-travel-api
    user: jenkins-sa
  name: jenkins-context
current-context: jenkins-context
users:
- name: jenkins-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ild3aDFQakVFc0MyMzF4THlUSlhnQTlucHNveENQWHAta2NERXdQWThEMlUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzU2NDQ4NzQyLCJpYXQiOjE3NTY0NDUxNDIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYTZiYWE4MDYtMWM4Yy00MjExLTgxYmQtNDA4MDQzMzRhMzM5Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJuZXctdHJhdmVsLWFwaSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJqZW5raW5zLXNhIiwidWlkIjoiYjc1OWVkOGYtODhmMy00ZjEyLWEzYTUtODU5MTg1OWM5ODM3In19LCJuYmYiOjE3NTY0NDUxNDIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpuZXctdHJhdmVsLWFwaTpqZW5raW5zLXNhIn0.eGgOy2NdT-hrUBTlxAkEX0ILekkdRAk_rHtT6JjJ4SF-pm4DJ1yFkhNEas6DyaIUUiKBd89zFNOwZjadv0GYXIIN-mSLLy_hnq6YKkaofvFmrlK6fk2RlD9D0kijkN_fb7eRW39d-wjDJdGogeFkjhzqHeh4shsStTZ2BSrPolaQ1UxVLm90qQYXzq_r4G9CnkgFFYxWpOJrw1aBdqSGPAlSxNEYUalWwjBiuALyYkuIg8n2gnPI1LAjGR97vX0kUZgInNqVdydGwmvaXGkQv36KLLUE6lmwLss9sxyn4EJXQWEji5H0tf2FuQUlrazrZbJEabEix0eYkNeeSIAjsQ
 
